### ISSUE TITLE
Credential fill button appears at invalid location, never disappears

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#945]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a website where login information can be filled by KeePassXC.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The "Fill credentials with KeePassXC" button appears in login fields and allows me to fill credentials with KeePassXC.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The "Fill credentials with KeePassXC" button appears in random locations and does nothing when clicked.

## Context
[NOTE]: # ( Give us any additional information you may have. )
The button also appears in _valid_ locations, but it also appears in invalid locations in addition to that.

![image](https://user-images.githubusercontent.com/1658949/87540569-34bba080-c6a0-11ea-8a87-e520bf7855ef.png)

I'm seeing this in the Chrome-based Edge.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
This happens with every site? Or just the one with the screenshot?

**Comment by oliversalzburg** [comment]
@varjolintu I've noticed it on several sites. So far, I've not been able to detect the pattern that causes it. I also can't reliably reproduce it yet, but it keeps happening.

**Comment by varjolintu** [comment]
What browser are you using? The issue template doesn't reveal that.

**Comment by oliversalzburg** [comment]
That's the new Chrome-based Edge.

**Comment by varjolintu** [comment]
That explains some because it's still one version number lower than the latest. Microsoft validation takes days.

**Comment by oliversalzburg** [comment]
By now I've upgraded and this is still happening on the same page. I haven't noticed it anywhere else though. Might be something weird with pgAdmin.

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment]
Please test this with https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.7.0-beta1
Instructions: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by oliversalzburg** [comment]
Seems to be stuck in a "Key exchange was not successful." state.

**Comment by varjolintu** [comment]
You'll also have to modify the JSON script to include the temporary extension's ID. Did you do that?

**Comment by oliversalzburg** [comment]
Yes, I did. I copied the `ID` prefix from the extensions page with it. That's why it wasn't working.

It's working now, and the behavior regarding this issue is unchanged.

**Comment by varjolintu** [comment]
Ok. Thank you for testing. I would need to setup an identical page for testing it myself.

**Comment by oliversalzburg** [comment]
This is pgAadmin and I'm running it through Docker. You may use this docker-compose.yml to start a similar environment.

```yml
version: "3.7"
services:
    postgres:
        image: postgis/postgis:10-3.0
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/postgres/data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
            PGDATA: /var/lib/postgresql/data/pgdata
    postgres-gui:
        image: dpage/pgadmin4
        ports:
            - "1234:80"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: postgres@localhost
            PGADMIN_DEFAULT_PASSWORD: postgres
```

The pgAdmin interface will be running at `localhost:1234` and use `postgres@localhost` as login with password `postgres`. The hostname, username and password of the server will be `postgres`.

When setting up the integration, password entry will be offered at this point:

![image](https://user-images.githubusercontent.com/1658949/91029161-b4714f00-e5fe-11ea-9c7b-b9330b5e5b72.png)

After confirming the dialog, that overlay icon will stay in its place:

![image](https://user-images.githubusercontent.com/1658949/91029258-d074f080-e5fe-11ea-8a3c-0bbf3eaf9a77.png)
